Repository samuel-gomez/react-starter-vitejs, pull requests merged in 2024-01, with the labels that each got.

#102 chore(packages): update @axa-fr/react-toolkit-all and @axa-fr/react-toolkit-core to version 2.2.0
  features/Demos/Accordion/Accordion.feature
  features/Demos/Action/Action.feature
  features/Demos/Alert/Alert.feature
  features/Demos/Badge/Badge.feature
  features/Demos/Button/Button.feature
  features/Demos/Card/Card.feature
  features/Demos/CheckboxInput/CheckboxInput.feature
  features/Demos/DateInput/DateInput.feature
  features/Demos/FileInput/FileInput.feature
  features/Demos/Footer/Footer.feature
  features/Demos/FooterClient/FooterClient.feature
  features/Demos/Header/Header.feature
  features/Demos/Help/Help.feature
  features/Demos/Infos/Infos.feature
  features/Demos/Loader/Loader.feature
  features/Demos/Modal/Modal.feature
  features/Demos/NavBar/NavBar.feature
  features/Demos/NumberInput/NumberInput.feature
  features/Demos/Popover/Popover.feature
  features/Demos/RadioInput/RadioInput.feature
  features/Demos/Restitution/Restitution.feature
  features/Demos/SelectInput/SelectInput.feature
  features/Demos/SelectMulti/SelectMulti.feature
  features/Demos/Slider/Slider.feature
  features/Demos/Stepper/Stepper.feature
  features/Demos/Switch/Switch.feature
  features/Demos/Table/Table.feature
  features/Demos/Tabs/Tabs.feature
  features/Demos/TextInput/TextInput.feature
  features/Demos/TextareaInput/TextareaInput.feature
  features/Demos/Title/Title.feature
  features/Demos/TitleBar/TitleBar.feature
  package-lock.json
  package.json
  src/shared/components/Editor/InputEditor/__tests__/__snapshots__/InputEditor.test.tsx.snap
Labels: dependencies

#100 Feat(shared table | demo): add row headers
  features/Demos/Employees/Employees.feature
  src/App/Routes/Routes.tsx
  src/App/Routes/constants.ts
  src/Layout/Menu/constants.ts
  src/pages/Demos/Employees/Employees.tsx
  src/pages/Demos/Employees/__tests__/Employees.spec.tsx
  src/pages/Demos/Employees/constants.ts
  src/pages/Demos/Employees/index.ts
  src/pages/Demos/Employees/tableData.json
  src/shared/components/Table/Body/Body.tsx
  src/shared/components/Table/Body/Line/Line.container.tsx
  src/shared/components/Table/Body/Line/Line.tsx
  src/shared/components/Table/Body/Line/__tests__/Line.test.tsx
  src/shared/components/Table/Body/types.d.ts
  src/shared/components/Table/Header/Header.tsx
  src/shared/components/Table/Header/index.ts
  src/shared/components/Table/Headers/Header/Header.tsx
  src/shared/components/Table/Headers/Header/Th/Th.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/SortingIcon.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/ThSortable.container.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/ThSortable.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/__tests__/SortingIcon.test.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/__tests__/ThSortable.container.test.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/__tests__/ThSortable.test.tsx
  src/shared/components/Table/Headers/Header/Th/ThSortable/index.ts
  src/shared/components/Table/Headers/Header/Th/__tests__/Th.test.tsx
  src/shared/components/Table/Headers/Header/Th/index.ts
  src/shared/components/Table/Headers/Header/__tests__/Header.test.tsx
  src/shared/components/Table/Headers/Header/index.ts
  src/shared/components/Table/Headers/Header/types.d.ts
  src/shared/components/Table/Headers/Headers.tsx
  src/shared/components/Table/Headers/__tests__/Headers.test.tsx
  src/shared/components/Table/Headers/index.ts
  src/shared/components/Table/Table.tsx
  src/shared/components/Table/index.ts
  src/shared/scss/custom.scss
  src/shared/testsUtils/sharedScenarios/table/table.ts
  src/shared/testsUtils/sharedScenarios/table/utils.ts
Labels: demo, accessibilité

#103 fix(table): cover and clean
  scripts/clean.js
  src/shared/components/Table/Headers/Header/__tests__/Header.test.tsx
  src/shared/testsUtils/sharedScenarios/table/utils.ts
Labels: bug

#104 fix(type): type node
  package-lock.json
  package.json
  scripts/files/package.json
Labels: bug
